name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
    
        - name: Pull latest Espressif IDF Docker Container
          run: |
            docker pull espressif/idf
    
        - name: Build Image
          run: |
            make build
